### ISSUE TITLE
INVALID_ARGUMENT on signer creation

### ISSUE THREAD

**Issue by jdponomarev** [zerodevapp/sdk-v1#35]
Hey guys, I'm getting this error when creating a signer based on your Getting started example.

```

/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/utils/errors.ts:656
            error = new TypeError(message);
                    ^
TypeError: no matching function (argument="key", value="address", code=INVALID_ARGUMENT, version=6.3.0)
    at makeError (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/utils/errors.ts:656:21)
    at assert (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/utils/errors.ts:680:25)
    at assertArgument (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/utils/errors.ts:692:5)
    at Interface.getFunctionName (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/abi/interface.ts:416:23)
    at buildWrappedMethod (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/contract/contract.ts:324:34)
    at Contract.getFunction (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/contract/contract.ts:770:22)
    at Object.get (/Users/jedi/Documents/c/custody/node_modules/ethers/src.ts/contract/contract.ts:701:39)
    at wrapProvider (/Users/jedi/Documents/c/custody/node_modules/@zerodevapp/sdk/src/Provider.ts:36:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getZeroDevProvider (/Users/jedi/Documents/c/custody/node_modules/@zerodevapp/sdk/src/index.ts:60:22) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'address'
}
```

I'm doing both options: using my own ethers wallet and using your wrapper.

```
const wallet = new ethers.Wallet("11111", provider);   
const signer = await getZeroDevSigner({
  projectId: ZERODEV_PROJECT_ID,
  owner: getPrivateKeyOwner("11111"), //Doesn't work
  // @ts-ignore
  // owner: wallet //Doesn't work too
})
```
I'm using node.js 18

**Comment by jdponomarev** [comment]
closing this. the issue was I'm using ethers 6+ and zerodev is using 5.7.2
